import { Lexend } from 'next/font/google';
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";



// Adding Lexend Deca font
const lexendDeca = Lexend({
  weight: '400', // You can specify different weights if needed
  subsets: ['latin'], // Specify subsets if necessary
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.variable} antialiased`}>
        <Header />
        <div className="container m-auto">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
